server:
  host: "0.0.0.0"
  port: 8001
  log_level: "ERROR"  # Уменьшаем уровень логирования для тестов

cors:
  allowed_origins:
    - "http://localhost:3080"
    - "http://localhost:8001"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

model:
  path: "models/Qwen3-4B-Instruct-2507-Q8_0.gguf" #"/dev/null"  # Фейковый путь для тестов
  name: "test-model"  # Важно: это значение должно совпадать с тестами
  ctx_size: 512
  gpu_layers: 0
  verbose: false

generation:
  default_temperature: 0.7
  default_max_tokens: 128
  stream: false

app:
  title: "Test API Service"
  description: "Test API service"
  version: "1.0.0-test"

monitoring:
  enabled: false

logging:
  level: "ERROR"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

caching:
  enabled: false
